name: Build xfce-test container

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 0' # https://crontab.guru/#0_4_*_*_0
  release:
    types:
      - published

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: docker.pkg.github.com/${{ github.repository }}

jobs:
  push_to_registry:
    # https://github.com/marketplace/actions/push-to-registry
    name: Build and Push container image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Read build args from environment
        # https://gist.github.com/judy2k/7656bfe3b322d669ef75364a46327836
        run: |
          eval "cat <<EOF
          $(egrep -v '^#' .env)
          EOF
          " | tee --append $GITHUB_ENV
          echo "${{ github.event_name }}"

      - if: github.event_name == 'schedule'
        run: echo "TAG=${DOWNLOAD_DATE}" >> $GITHUB_ENV
      - if: github.event_name == 'release'
        run: echo "TAG=${GITHUB_REF}" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        run: echo "TAG=${GITHUB_SHA:0:12}" >> $GITHUB_ENV

      - name: Build container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: xfce-test-archlinux
          oci: false
          tags: latest ${{ env.TAG }}
          dockerfiles: |
            ./Dockerfile
          build-args: |
            ACTIONS_CI=${{ env.ACTIONS_CI }}
            TRAVIS_CI=${{ env.TRAVIS_CI }}
            USER_NAME=${{ env.USER_NAME }}
            USER_SHELL=${{ env.USER_SHELL }}
            DISPLAY=${{ env.DISPLAY }}
            MAIN_BRANCH=${{ env.MAIN_BRANCH }}
            DOWNLOAD_DATE=${{ env.DOWNLOAD_DATE }}
            PACMAN_HELPER=${{ env.PACMAN_HELPER }}
            PACMAN_HELPER_URL=${{ env.PACMAN_HELPER_URL }}
            CONTAINER_BASE=${{ env.CONTAINER_BASE }}
            CFLAGS=${{ env.CFLAGS }}
            CPPFLAGS=${{ env.CPPFLAGS }}
          extra-args: |
            --pull

      - name: Push to Github Registry
        id: push-to-gh
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-gh.outputs.registry-paths }}"
