name: Build xfce-test container

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 0' # https://crontab.guru/#0_4_*_*_0
  release:
    types:
      - published

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push_to_registry:
    # https://github.com/marketplace/actions/push-to-registry
    name: Build and Push container image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Read and setup build args from environment
        # https://gist.github.com/judy2k/7656bfe3b322d669ef75364a46327836
        run: |
          eval "cat <<EOF
          $(grep -Ev '^#' .env)
          EOF
          " | tee --append $GITHUB_ENV

          mkdir --parents ${GITHUB_WORKSPACE}/build
          setfacl --default --modify u::rwx,g::rwx,o::- ${GITHUB_WORKSPACE}/build

          case "${{ github.event_name }}" in
            schedule) echo "TAG=${DOWNLOAD_DATE}" ;;
            release) echo "TAG=${GITHUB_REF}" ;;
            push) echo "TAG=${GITHUB_SHA:0:12}" ;;
          esac | tee --append $GITHUB_ENV

          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#multiline-strings
          echo 'TIMESTAMP<<EOF' | tee --append $GITHUB_ENV
          date --date="${DOWNLOAD_DATE}" '+%s' | tee --append $GITHUB_ENV
          echo 'EOF' | tee --append $GITHUB_ENV

      - name: Build container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: xfce-test-archlinux
          oci: false
          tags: latest ${{ env.TAG }}
          dockerfiles: |
            ./Dockerfile
          build-args: |
            ACTIONS_CI=${{ env.ACTIONS_CI }}
            TRAVIS_CI=${{ env.TRAVIS_CI }}
            USER_NAME=${{ env.USER_NAME }}
            USER_SHELL=${{ env.USER_SHELL }}
            CONTAINER_BASE=${{ env.CONTAINER_BASE }}
            DISPLAY=${{ env.DISPLAY }}
            MAIN_BRANCH=${{ env.MAIN_BRANCH }}
            DOWNLOAD_DATE=${{ env.DOWNLOAD_DATE }}
            PACMAN_HELPER=${{ env.PACMAN_HELPER }}
            PACMAN_HELPER_URL=${{ env.PACMAN_HELPER_URL }}
            CFLAGS=${{ env.CFLAGS }}
            CPPFLAGS=${{ env.CPPFLAGS }}
          extra-args: |
            --timestamp ${{ env.TIMESTAMP }}
            --userns=host
            --volume=${{ github.workspace }}/build:/tmp:U
        timeout-minutes: 50

      - name: Push to Github Registry
        id: push-to-gh
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-gh.outputs.registry-paths }}"

      - name: Upload Build Packages logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-log@${{ env.TAG }}
          # workaround for: https://github.com/actions/upload-artifact/issues/192
          path: |
            !${{ github.workspace }}/**/aurutils*
            ${{ github.workspace }}/build/**/*-log.gz
          retention-days: 7
